
name: Deployment Gold BEJ 12
run-name: ${{ github.actor }} is deploying out GitHub Actions 🚀

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: '34.31.195.255'
          username: 'root'
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            git config --global --add safe.directory /home/faruuq/

            # curl -sL https://deb.nodesource.com/setup_20.x | sudo -E bash -
            # apt install -y nodejs

            # npm install -g npm@latest

            # Ensure pm2 is installed
            # npm install -g pm2

            # Change to the project directory and execute the build script
            /home/faruuq/
            git reset --hard; git clean -xdf
            git pull
            npm i
            pm2 delete main
            pm2 start main.js
